[project]
name = "chinese-text-anki-analyser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chinese-converter>=1.1.1",
    "davia>=0.1.13",
    "jieba>=0.42.1",
    "pandas>=2.2.3",
]
